import Footer from "@/components/footer/Footer";
import { NavbarDemo } from "@/components/navbar/Navbar-aceternity";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased relative`}
      >
        {/* <Navbar /> */}
        <NavbarDemo />
        {children}
        <Footer />
      </body>
    </html>
  );
}
