import type { Metadata } from "next";
import "./globals.css";
import { Nunito } from 'next/font/google';
import { NavbarDesktop } from "@/components/navbar/Navbar-desktop";
import NavbarMobile from "@/components/navbar/Navbar-mobile";
import Footer from "@/components/footer/Footer";

const font = Nunito({ subsets: ['latin'], weight: ['400', '500', '600', '700', '800', '900'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body
        className={`${font.className} antialiased relative`}
      >
        <NavbarDesktop />
        <NavbarMobile />
        {children}
        <Footer />
      </body>
    </html>
  );
}
