import Footer from "@/components/footer/Footer";
import { NavbarDesktop } from "@/components/navbar/Navbar-desktop";
import type { Metadata } from "next";
import "./globals.css";
import NavbarMobile from "@/components/navbar/Navbar-mobile";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased relative`}
      >
        <NavbarDesktop />
        <NavbarMobile />
        {children}
        <Footer />
      </body>
    </html>
  );
}
